package auto.addressbook.tests;// Generated by Selenium IDE

import auto.addressbook.model.GroupData;
import org.junit.Test;

public class DeleteGroupTest extends TestBase {

  @Test
  public void testGroupDeletion() {
    app.getNavigationHelper().gotoGroupPage();
    if (! app.getGroupHelper().isThereAGroup()) {
      app.getGroupHelper().CreateGroup(new GroupData("test2", null,null));
    }
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroup();
    app.getGroupHelper().returnToGroupPage();
  }

}
