package auto.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;

public class DeleteGroupTest extends TestBase {

  @Test
  public void testGroupDeletion() {
    app.gotoGroupPage();
    app.getGroupHelper().selectGroup();
    app.deleteSelectedGroup();
    app.getGroupHelper().returnToGroupPage();
  }

}
