package auto.addressbook.tests;// Generated by Selenium IDE

import auto.addressbook.model.GroupData;
import org.junit.Test;

public class GroupCreationTest<JavascriptExecutor> extends TestBase {

  @Test
  public void testGroupCreation() {
    app.getNavigationHelper().gotoGroupPage();
    app.getGroupHelper().fillGroupForm(new GroupData("test2", "test", "test"));
    app.getGroupHelper().submitGroupCreation();
    app.getGroupHelper().returnToGroupPage();
  }

}
